#!/usr/bin/env sh
#
# A naive script to endlessly play the current song
# this script is part of
#    <https://codeberg.org/tcheukueppo/scripts.git>
#
#                                  Author: kueppo

curs="$(nc -U -q0 /tmp/sad-sock <<< "status songid" | fgrep songid)"
if test -z "$curs"; then
	printf "%s: couldn't get current song id" "$0"
	exit 1
fi
pid="$(pidof sad)"
while test -d "/proc/$pid"; do
	nid="$(nc -U -q0 /tmp/sad-sock <<< "status songid"| fgrep songid)" 
	if test "$nid" != "$curs"; then
		nc -U -q0 /tmp/sad-sock <<< "play ${curs##* }"
	fi
	sleep 0.1
done
