#!/usr/bin/env sh
#
# select a song to play from dmenu
# this script is part of
#    <https://codeberg.org/tcheukueppo/scripts.git>
#
#                                  Author: kueppo


sock='/tmp/sad-sock'
temp='/tmp/plist'

song=$(echo playlist | nc -q0 -U $sock | grep -v '^OK' | \
		grep -v '^ERR' | tee $temp | sed -n 's/^.*\/\(.*\)$/\1/p' | \
		sort | dmenu -i -l 10) 
if test x"$song" != x""; then
	pkill -fu "$USER" '/sadr$'
	id=$(cat $temp | fgrep "$song" | cut -d: -f1 | head -n 1)
	test -n $id && printf 'play %s\n' "$id" | nc -q0 -U "$sock"
fi
