#!/usr/bin/env sh
#
# installation program of all the scripts and services
# expected to to be in this program's parent directory
#
# get more information here:
#         <https://codeberg.com/tcheukueppo/scripts.git>

gpwd="$(pwd)"
if test "$(basename gpwd)" = scripts; then
	echo 'ERR: run it in scripts!'
	exit 1
fi

# copy all executable scripts except me!
echo 'installing scripts in $HOME/.local/bin'
mybin="$HOME/.local/bin"
mkdir -p "${mybin%bin}" && mkdir -p "$mybin"
for i in *; do
	if test "$i" != "${0#./}"; then
		if test -f "$i"; then
			test -x "$i" && cp -v "$i" "$mybin"
		fi
	fi
done

# Os specific scripts
case "$(uname)" in
Linux) cp -v Linux/* "$mybin" 2>/dev/null;;
BSD) cp -v BSD/* "$mybin" 2>/dev/null;;
*) :;;
esac

# installing systemd/init services
config="${XDG_CONFIG_HOME:-"$HOME/.config"}"
mkdir -p "$config"

if which systemd-run >/dev/null 2>&1; then
	echo "installing systemd services"
	test -d Linux/systemd && cp -rv Linux/systemd "$config"
else
	echo "installing init rc services"
	:
fi
