#!/usr/bin/env sh
#
# a simple script which finds for pdfs
# and open them with mupdf pdf viewer

if ! command -v mupdf; then
	printf 'install mupdf first!'
	exit 1
fi

case $# in
0)	# default search directory
	db='/mnt2/books' ;;
1)	if ! test -d "$1"; then
		printf '%s: %s is not a directory\n' "$0" "$1"
		exit 1
	fi
	db="$1" ;;
*)	printf '%s: max argument is 2, min argument is 2\n' "$0" ;;
esac

cache="${XDG_HOME_CACHE:-"$HOME/.cache"}"
dcache="${cache}/mdocs"

pdf="$(find $db -type f \
		\( -iname '*.pdf' -or \
			-iname '*.xps' -or \
			-iname '*.chm' -or \
			-iname '*.cbz' -or \
			-iname '*.epub' \
		\)
		 -print | tee $dcache | \
		while read base; do
			echo "$(basename "$base")"
		done | dmenu -i -l 20)"

if test -n "$pdf"; then
	pdf="$(cat $dcache | fgrep "$pdf")"
	mupdf "$pdf"
fi
