#!/usr/bin/env sh
# private script use to push projects to all remote
# repositories (codeberg, gitlab, github)
push()
{
	local lbranch="${1:-master}"
	local rbranch="${2:-master}"
	# assume local project name is the same as that of 
	# remote repository
	local cwd="$(basename $PWD)"
	for i in $remote1 $remote2 $remote3
	do
		read -p "push on $i(y/n)?" answer
		if [ "$answer" = y ] || [ "$answer" = Y ]
		then
			printf "Preparing to push local branch to %s/%s\n" $i $cwd
			git push "${i}/${cwd}.git" "${lbranch}:${rbranch}"
		fi
	done
}

push_all()
{
	local answer
	local checkrepo='false'
	for i in *
	do
		if [ -d "$i" ] && [ -d "$i/.git" ]
		then
			checkrepo='true'
			read -p  "push on $i(y/n)?" answer
			[ "$answer" = y ] || [ "$answer" = Y ] && cd "$i" && push && cd -
		fi
	done
	$(echo $checkrepo) || printf "no repositories found here\n" >&2
}

xyz()
{
	echo "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"
}

remote1="https://$(xyz)@github.com/tcheukueppo"
remote2='https://codeberg.org/tcheukueppo'
remote3='https://gitlab.com/tcheukueppo'

exitcode=0
case $# in
0)	push ;;
1)	[ "$1" = 'all' ] && push_all || exitcode=1 ;;
2)	push "$1" "$2" ;;
*)	exitcode=1 ;;
esac
[ $exitcode = 1 ] && printf "Invalid arguments\n" >&2
