#!/usr/bin/env sh

# search for docs

if ! which zathura &>/dev/null; then
	echo "ERR: $0 depends on zathura"
	exit 1
fi

docsd='/mnt2/books'
cache="${XDG_HOME_CACHE:-"$HOME/.cache"}"
docache="${cache}/zdocs"

test -d "$docsd" &>/dev/null || exit 1
if test -z "$(cat $docache >/dev/null 2>&1)"; then
	find $docsd -type f -iname '*.pdf' | tee $docache &>/dev/null
fi

doc="$(cat $docache | sed -n 's/^.*\/\(.*\)$/\1/p' | dmenu -l 20 -i)"
doc="$(cat $docache | fgrep "$doc")"
test -n "$doc" && zathura "$doc"
