#!/bin/sh

[ -d "/mnt2/books" ] && [ -r "/mnt2/books" ] && direcs="/mnt2/books"
[ -d "$HOME/Downloads" ] && [ -r "$HOME/Downloads" ] && direcs="$direcs${direcs:+" "}$HOME/Downloads"
[ -d "$HOME/Documents" ] && [ -r "$HOME/Documents" ] && direcs="$direcs${direcs:+" "}$HOME/Documents"
 
if [ -n "$direcs" ]; then

	cache="${XDG_HOME_CACHE:-"$HOME/.cache"}"
	dcache="${cache}/zdocs"
	pdf="$(find $direcs -type f -iname '*.pdf' -print | tee "$dcache" | while read base; do echo `basename "$base"`; done | dmenu -c -p "Search" -z 600 -l 20 -h 20 -i)"
	pdf="$(cat "$dcache" | grep "/$pdf$" | head -n1)"

	[ -n "$pdf" ] && zathura "$pdf"
fi
