#!/usr/bin/env sh
#
# a simple script which finds for pdfs
# and open them with zathura pdf viewer

if ! command -v zathura; then
	echo 'install zathura first!' >&2
	exit 1
fi

db='/mnt2/books'

case $# in
1)	if ! test -d "$1"; then
		echo "$0: $1 is not a directory" >&2
		exit 1
	fi
	db="$1" ;;
*)	echo "$0 takes only one arguments" >&2 ;;
esac

cache="${XDG_HOME_CACHE:-"$HOME/.cache"}"
dcache="${cache}/zdocs"

pdf="$(find $db -type f -iname '*.pdf' -print | tee "$dcache" | \
		while read base; do
			echo "$(basename "$base")"
		done | dmenu -i -l 10)"

if test -n "$pdf"; then
	# if there are PDFs having the same name
	# but found in different directories, then 
	# take the first one
	pdf="$(cat "$dcache" | grep "/$pdf$" | head -n1)"
	zathura "$pdf"
fi
