#!/bin/sh

start_viper() {
	path="$1"

	[ -e "$path" ] && { printf "%s already exist in file system\n" "$path"; return; }
 
	> "$path" 1>/dev/null 2>&1 && rm -f "$path" || { printf "cannot write to '%s'\n", "$1"; return; }

	ffmpeg -video_size 1600x900 \
	       -framerate 100        \
		   -f x11grab           \
		   -i :0.0+0,0          \
		   -f pulse             \
		   -i alsa_output.pci-0000_00_1b.0.analog-stereo.monitor \
		   -ac 2                \
		   "$path" >/dev/null 2>&1 &

	[ -e /tmp/ffmpeg/record ] && kill `cat /tmp/ffmpeg_record` >/dev/null 2>&1
	printf "%s" "$!" > /tmp/ffmpeg_record
}

kill_viper() {
	kill `cat /tmp/ffmpeg_record` >/dev/null 2>&1
}

usage() {
	printf "viper start /path/to/output|stop\n";
}

case $# in
	1) [ "$1" == stop  ] && kill_viper || usage ;;
	2) [ "$1" == start ] && start_viper "$2" ;;
	*) usage ;;
esac
