#!/bin/sh

if test $# -ne 1; then printf "usage: chwal /path/to/image\n"; exit 1; fi

apply_st_background_image() {
	image="$1"

	if test -f "$image"; then
		bool=true
		for tool in ff-{blur,border,bright}; do
			command -v "$tool" >/dev/null || { printf "%s not found\n" $tool; bool=false; }
		done
		test $bool == false && return 1

		extension="${image##*.}"
		if test -n "$extension"; then
			program="${extension}2ff"

			if command -v "$program" >/dev/null; then
				$program < "$image" | ff-border e 50 | ff-bright rgba 0 0.5 1 | ff-blur 50 15 > "$HOME/.st.ff"
			else
				printf "'%s' not found\n" $program
				return 1
			fi
		else
			printf "file extension required\n"
		fi
	fi
}

change_wallpaper() { :; }

apply_st_background_image "$1"
#change_wallpaper "$1"
