#!/usr/bin/env sh
#
# script to create a ussd(Unstructured supplementary Service Data)
# session through a 3GPP network

getidex=0
stat=false

if ! command -v mmcli &>/dev/null; then
	echo 'mmcli not present, install ModemManager' >&2
	exit 1
elif test $# -ne 0; then
	echo 'arguments are not required, just run sussd' >&2
	exit 1
fi

getidex="$(mmcli -L | cut -d/ -f6 | cut -d ' ' -f1)"
if ! echo "$getidex" | grep -q '[0-9]\+'; then 
	echo "could not get modem index" >&2
	exit 1
fi

trapped() {
	${stat} && mmcli -m $getidex --3gpp-ussd-cancel
}

prompt() {
	trap 'trapped' SIGINT SIGQUIT
	local query=''

	while read -p '> ' query; do
		if test -z "$query"; then
			continue
		elif echo $query | grep -q '^\*[\*0-9]*#$'; then
			${stat} && mmcli -m $getidex --3gpp-ussd-cancel &>/dev/null
			mmcli -m $getidex --3gpp-ussd-initiate="$query" | perl -e "
				my \$line = undef;
				while(<<>>) {
					\$line .= \$_;
				}

				\$_ = \$line;
				if (/^.*:\\s+'(.*)'\$/s) {
					print \$1, \"\\n\";
				}"
			stat=true
			continue
		fi
		case "$query" in
		e|q|exit|quit)
			${stat} && mmcli -m $getidex --3gpp-ussd-cancel
			break ;;
		[0-9]|[0-9][0-9]|[0-9][0-9][0-9]|\#|\*)
			mmcli -m $getidex --3gpp-ussd-respond="$query" ;;
		*)
			echo 'invalid query' >&2 ;;
		esac
	done
	printf '\n'
}

prompt
