#!/bin/sh

readonly program="${0##*/}"

# default visibility of the project
access=false

main() {
	if [ $# -eq 1 -a \( "$1" = -h -o "$1" = --help \) ]
	then
		usage; return
	elif [ $# -lt 6 ]
	then
		usage && die "invalid number of arguments"
	fi

	while [ $# -ne 0 ]; do
		case $1 in
			-p) access=true; shift ;;
			-r) remote=$2; shift 2 ;;
			-n) name=$2; shift 2   ;;
			-d) descript=$2; shift 2 ;;
			 *) usage; exit 1        ;;
		esac
	done
	create_repo
}

die() { printf "%s: %s\n" "$pname" "$*"; exit 1; }

usage() {
	printf "usage:"
	printf "     gcreate [-p] -r <gitlab.com|codeberg.org|...> -n <repo_name> -d <description>"
	printf "     gcreate --help|-h"
}

create_repo() {

	header=; data=; api_url=
	service=${name%.*}

	if [ "$service" = codeberg ]
	then
		api_url="https://codeberg.org/api/v1/user/repos"
		header="Authorization: token $(tok github)"
		data='{"default_branch":"master","description":"'"$descript"'","license":"GPL3","name":"'$name'","private":'$access',"template":true,"trust_model":"default"}'                                               \
	elif [ "$service" = github ]
	then
		api_url="https://api.github.com/user/repos"
		header="Authorization: token $(tok codeberg)"
		data='{"name":"'$name'","private":'$access'}'
	elif [ "$service" = gitlab ]
	then
		api_url="https://gitlab.com/api/v4/projects/"
		header="PRIVATE-TOKEN: $(tok gitlab)"
		data='{"name":"'$name'","initialize_with_readme":"false"}'
	else
		die "cannot handle token for such service"
	fi

	curl --request POST       \
	     --header  "$header"  \
	     --data    "$data"    \
	     --url     "$api_url" >/dev/null 2>&1
}

command -v tok >/dev/null || die "$pname: tok not found"
main "$@"
