#!/bin/sh

have_curl_and_tok() {
	command -v curl tok >/dev/null 
	if [ $? -ne 0 ] 
	then
		printf "pub depends on: tok, curl!!\n" >&2
		return 1
	fi
}

change_visibility() {

	# check if repo name is valid
	printf "$1" | grep -q '[-a-zA-Z]\+' 
	if [ $? -ne 0 ]
	then
		printf "invalid '%s'\n" "$2"
		return 1
	fi

	# either public or private, nothing else
	if [ "$2" = private -o "$2" = public ]
	then
		printf "invalid '%s'\n" "$2"
		return 1
	fi

	# consume the API
	curl \
	  --request PATCH \
	  --header  "Accept: application/vnd.github+json"         \
	  --header  "Authorization: token $(tok github)"          \
	  --url     "https://api.github.com/repos/tcheukueppo/$1" \
	  --data    '{"name":"'"$1"'","description":"'"$3"'","homepage":"https://github.com"}'
}

if [ $# -ne 3 ]
then
	printf "usage:\n"
	printf "  pub <github_repo_name> <true|false>\n"
	exit 1
fi

if have_curl_and_tok
then
	change_visibility "$@"
fi
