#!/usr/bin/env perl

use strict;
use feature qw(say state);

my $gitlab   = q(Q9hZf-hbSdkhTvlb_eM6MjW1yq);
my $github   = q(Qph_KXKYU7Af139CP2H8pPD4Oy5PW4r0GuuhdkKb);
my $codeberg = q(TrorZrvZvtTMSYtuvPSTZuWrvMlxZtxPTyVSuSlW);

sub xcrypt {
	my $token = shift;	
    my $inc = sub { state $val = -1; $val == 9 ? q() : ++$val };

    local @ARGV = ( "$ENV{HOME}/.kit" );
    chomp( my $okey = <> );

    my $key  = join '', map { $_ . uc . $inc->() } split '', $okey;
    my $ekey = reverse $key;

    if ( $token =~ /^git(?:hub|lab)|codeberg$/ ) {
		eval "\$token = \${$token}; \$token =~ tr/$key/$ekey/"
	}
	else {
		eval "\$token =~ tr/$ekey/$key/";
	}

    say $token;
}

xcrypt @ARGV if $#ARGV == 0;
